[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
syntax = { path = "../syntax" }
messages = { path = "../messages" }
codespan-reporting = { workspace = true }