[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
messages = { path = "../messages" }
logos = "0.12.1"

[build-dependencies]
logos = "0.12.1"
build-deps = "0.1.4"
